name: Caller CI/CD WorkflowTest

on:
  push:
    branches:
      - Test
  pull_request:
    branches:
      - Test

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
    with:
      bucket: S3_ORIGIN_BUCKET_TEST
      ambiente: GITHUB_REF
    secrets: inherit
