name: Caller CI/CD Workflow

on:
  workflow_call:

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
    with:
      pom_path: env.BRANCH_NAME
    secrets: inherit
