name: Caller CI/CD WorkflowDev

on:
  workflow_dispatch:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/workflow-dev.yml@main
    secrets: inherit
