name: Caller CI/CD Workflow

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  cicd-caller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Branch Name and Trigger Main Workflow
        uses: actions/github-script@v5
        with:
          script: |
            const branchName = github.context.payload.ref.replace('refs/heads/', '');
            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml',
              inputs: {
                branchname: branchName,
              },
            });

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
