name: Caller CI/CD WorkflowProd
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/workflow-prod.yml@main
    secrets: inherit
