name: Caller CI/CD WorkflowTest

on:
  push:
    branches:
      - Test
  pull_request:
    branches:
      - Test

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/workflow-test.yml@main
    secrets: inherit
