name: Caller CI/CD WorkflowProd

on:
  push:
    branches:
      - Prod
  pull_request:
    branches:
      - Prod

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
    with:
      bucket: S3_ORIGIN_BUCKET_PROD
    secrets: inherit
