name: Caller CI/CD Workflow

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  ReusableJobForCICD:
    runs-on: ubuntu-latest
    needs: set_branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Reusable Job For CI/CD
        uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
        with:
          BRANCH_NAME: ${{ needs.set_branch.outputs.BRANCH_NAME }}
        env:
          BRANCH_NAME: ${{ needs.set_branch.outputs.BRANCH_NAME }}

  set_branch:
    runs-on: ubuntu-latest
    outputs:
      id: set_branch
      setBranchOutput: ${{ steps.set_branch.outputs.BRANCH_NAME }}
    steps:
      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'push' && github.event.ref }} " >> $GITHUB_ENV
