name: Caller CI/CD Workflow
on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  ReuseableJobForCICD:
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'push' && github.event.ref }} " >> $GITHUB_ENV

      - name: Run Reusable Job For CI/CD
        uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
        env:
          BRANCH_NAME: ${{ steps.set_branch.outputs.BRANCH_NAME }}
        secrets: inherit