name: Caller CI/CD Workflow

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  callerCICD:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to S3
        uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd-frontend.yml@main
        with:
          CI_ENV: ${{ { github.ref } }} 
