name: Caller CI/CD WorkflowDev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/workflow-dev.yml@main
    secrets: inherit
