name: Frontend Test (parallel)

on:
  push:
    branches:
      - Dev
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: node:19

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge']

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}
        options: --shm-size=2gb

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn install

      - name: Build Frontend
        run: yarn build

      - name: Start Docker Container
        run: docker run -d --name my-frontend-app -p 8080:80 my-frontend-app

      - name: Wait for Container to Start
        run: sleep 10

      - name: Run Tests
      - run: npm run test
        env:
          BROWSER: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.browser }}
          path: screenshots/
