name: Frontend Test

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  FrontEndTest:
    name: FrontEndTest
    runs-on: ubuntu-latest

    container:
      image: node:14

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge']

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}
        options: --shm-size=2gb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Test code
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Chequeos
        run: |
          ls
          echo "ls en dist"
          ls dist/

      - name: Upload Artifact with JAR file
        uses: actions/upload-artifact@v3
        with:
          name: "pagina"
          path: dist/
      - run: npm run test
        env:
          BROWSER: ${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
