name: Github Action Workflow PROD

on:
  push:
    branches:
      - Prod
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  FrontEndTest:
    needs: SonarTest
    name: FrontEndTest
    runs-on: ubuntu-latest

    container:
      image: node:19

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
      - run: npm ci
      - run: npm run test
        env:
          BROWSER: ${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/

  build-dev:
    needs: FrontEndTest
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      CI_ENV: Prod
      CONTENTFUL_ENVIRONMENT: 'Prod'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_PROD }}
