name: Github Action Workflow DEV

on:
  push:
    branches:
      - Dev
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-dev:
    needs: SonarTest
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      CI_ENV: Dev
      CONTENTFUL_ENVIRONMENT: 'Dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_DEV }}
