name: Github Action Workflow PROD

on:
  push:
    branches:
      - Prod
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        command: ["dockerd", "--host=0.0.0.0", "--add-runtime=nvidia=/usr/bin/nvidia-container-runtime"]

    steps:
      obs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        command: ["dockerd", "--host=0.0.0.0", "--add-runtime=nvidia=/usr/bin/nvidia-container-runtime"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t temporalImage .

      - name: Run Docker container
        run: docker run -d --name temporalContainer temporalImage

      - name: Copy files to Docker container
        run: docker cp . my-container:/app

      - name: Generate yarn.lock
        run: docker exec temporalContainer yarn install --frozen-lockfile

      - name: Start application
        run: docker exec temporalContainer yarn start

      - name: Wait for the application to start
        run: sleep 30

      - run: npm run test
        env:
          BROWSER: ${{ github.event.inputs.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/

      - name: Stop and remove Docker container
        run: docker stop temporalContainer && docker rm temporalContainer
